dealer = {
    "city": "Самара",
    "where": "Самаре",
}
# Словарь соответствия цветов
model_mapping = {
    "BJ40": {
        "folder": "bj40",
        "color": {
            "black": "black",
            "blue": "blue",
            "green": "green",
            "light-blue": "light-blue",
            "red": "red",
            "white": "white",
            "Черный": "black",
            "Синий": "blue",
            "Зеленый": "green",
            "Светло-синий": "light-blue",
            "Голубой": "light-blue",
            "Красный": "red",
            "Белый": "white",
        }},
    "U5 Plus": {
        "folder": "u5-plus",
        "color": {
            "black": "black",
            "gray": "gray",
            "red": "red",
            "white": "white",
            "Черный": "black",
            "Серый": "gray",
            "Красный": "red",
            "Белый": "white",
        }},
    "X35": {
        "folder": "x35",
        "color": {
            "blue": "blue",
            "bronze": "bronze",
            "red": "red",
            "white": "white",
            "Синий": "blue",
            "Коричневый": "bronze",
            "Красный": "red",
            "Белый": "white",
        }},
    "X35": {
        "folder": "x55",
        "color": {
            "gray-with-black-roof": "gray-with-black-roof",
            "gray": "gray",
            "light-gray-with-black-roof": "light-gray-with-black-roof",
            "light-gray": "light-gray",
            "red-with-black-roof": "red-with-black-roof",
            "red": "red",
            "white-with-black-roof": "white-with-black-roof",
            "white": "white",
            "yellow-with-black-roof": "yellow-with-black-roof",
            "yellow": "yellow",
            "Серый/черный": "gray-with-black-roof",
            "Серый": "gray",
            "Светло-серый/черный": "light-gray-with-black-roof",
            "Светло-серый": "light-gray",
            "Красный/черный": "red-with-black-roof",
            "Красный": "red",
            "Белый/черный": "white-with-black-roof",
            "Белый": "white",
            "Желтый/черный": "yellow-with-black-roof",
            "Желтый": "yellow",
        }},
    "X7": {
        "folder": "x7",
        "color": {
            "black": "black",
            "gray": "gray",
            "silver": "silver",
            "white": "white",
            "Черный": "black",
            "Серый": "gray",
            "Серебристый": "silver",
            "Белый": "white",
        }},
    # ... добавьте другие модели по мере необходимости
}