dealer = {
    "city": "Самара",
    "where": "Самаре",
}
# Словарь соответствия цветов
model_mapping = {
    "BJ40": {
        "folder": "bj40",
        "color": {
            "black": "black.png",
            "blue": "blue.png",
            "green": "green.png",
            "light-blue": "light-blue.png",
            "red": "red.png",
            "white": "white.png",
            "Черный": "black.png",
            "Синий": "blue.png",
            "Зеленый": "green.png",
            "Светло-синий": "light-blue.png",
            "Голубой": "light-blue.png",
            "Красный": "red.png",
            "Белый": ".pngwhite",
        }},
    "U5 Plus": {
        "folder": "u5-plus",
        "color": {
            "black": "black.png",
            "gray": "gray.png",
            "red": "red.png",
            "white": "white.png",
            "Черный": "black.png",
            "Серый": "gray.png",
            "Красный": "red.png",
            "Белый": "white.png",
        }},
    "X35": {
        "folder": "x35",
        "color": {
            "blue": "blue.png",
            "bronze": "bronze.png",
            "red": "red.png",
            "white": "white.png",
            "Синий": "blue.png",
            "Коричневый": "bronze.png",
            "Красный": "red.png",
            "Белый": "white.png",
        }},
    "X35": {
        "folder": "x55",
        "color": {
            "gray-with-black-roof": "gray-with-black-roof.png",
            "gray": "gray.png",
            "light-gray-with-black-roof": "light-gray-with-black-roof.png",
            "light-gray": "light-gray.png",
            "red-with-black-roof": "red-with-black-roof.png",
            "red": "red.png",
            "white-with-black-roof": "white-with-black-roof.png",
            "white": "white.png",
            "yellow-with-black-roof": "yellow-with-black-roof.png",
            "yellow": "yellow.png",
            "Серый/черный": "gray-with-black-roof.png",
            "Серый": "gray.png",
            "Светло-серый/черный": "light-gray-with-black-roof.png",
            "Светло-серый": "light-gray.png",
            "Красный/черный": "red-with-black-roof.png",
            "Красный": "red.png",
            "Белый/черный": "white-with-black-roof.png",
            "Белый": "white.png",
            "Желтый/черный": "yellow-with-black-roof.png",
            "Желтый": "yellow.png",
        }},
    "X7": {
        "folder": "x7",
        "color": {
            "black": "black.png",
            "gray": "gray.png",
            "silver": "silver.png",
            "white": "white.png",
            "Черный": "black.png",
            "Серый": "gray.png",
            "Серебристый": "silver.png",
            "Белый": "white.png",
        }},
    # ... добавьте другие модели по мере необходимости
}